// Generated by CoffeeScript 1.7.1
(function() {
  var addEntry, addEntryInput, api, currentBlog, fetchEntries, initEvents, initMicroblogViewer, isEnteringInput, iwcCallback, iwcManager, loadComments, login, microblogLib, requestSender;

  api = i5.las2peer.jsAPI;

  microblogLib = i5.las2peer.microblog;


  /*
    Check explicitly if gadgets is known, i.e. script is executed in widget environment.
    Allows compatibility as a Web page.
   */

  if (typeof gadgets !== "undefined" && gadgets !== null) {
    iwcCallback = function(intent) {

      /*
        Get the selected blog from intend and fetch the contents.
       */
      if (intent.action === "MICROBLOG_SELECTED") {
        return fetchEntries(intent.data);
      }
    };
    iwcManager = new api.IWCManager(iwcCallback);
  }

  login = new api.Login(api.LoginTypes.HTTP_BASIC);

  login.setUserAndPassword(clientDefaults.userName, clientDefaults.userPassword);

  requestSender = new api.RequestSender(clientDefaults.address, login);

  isEnteringInput = false;

  currentBlog = "";

  $(document).ready(function() {
    initMicroblogViewer();
  });

  initMicroblogViewer = function() {
    initEvents();
  };

  initEvents = function() {
    return $("#addEntry").click(function() {
      addEntryInput();
    });
  };


  /*
    Creates multiline input field to create new entries.
   */

  addEntryInput = function() {
    if (isEnteringInput || currentBlog.length === 0) {
      return 0;
    }
    microblogLib.ElementGenerator.generateMultilineTextfield($("#content"));
    $("#sendEntryButton").click(function(e) {
      addEntry();
    });
    isEnteringInput = true;
    $("#enterBlogEntry").focus();
  };


  /*
    Removes input field and notifies service about new entry.
   */

  addEntry = function() {
    var entry;
    entry = $("#enterBlogEntry").val().trim();
    isEnteringInput = false;
    $("#textfieldBox").remove();
    if (entry.length > 0) {
      requestSender.sendRequest("post", "blogs/" + currentBlog, entry, function(data) {
        fetchEntries(currentBlog);
      });
    }
  };


  /*
    Fetches all entries from a selected blog.
   */

  fetchEntries = function(blog) {
    currentBlog = blog;
    $("#content").html("");
    requestSender.sendRequest("get", "blogs/" + blog, "", function(data) {
      var $xml, $xmlInner, requests, xml;
      xml = $.parseXML(data);
      $xml = $(xml);
      $("#header .title").text($xml.find("resource").attr("name"));
      requests = [];
      $xmlInner = [];

      /*
        For each child (i.e.) entry get the respective ressource.
        Create a bunch of requests and use a global variable to store the results.
       */
      $xml.find("child").each(function(index) {
        requests[index] = new api.Request("get", "entries/" + $(this).attr("id"), "", function(childData) {
          var xmlInner;
          xmlInner = $.parseXML(childData);
          $xmlInner[index] = $(xmlInner).find("resource");
        });
      });

      /*
        Send all requests asynchroniusly and when they are done, create new elements in the html.
       */
      requestSender.sendRequestsAsync(requests, function() {
        microblogLib.ElementGenerator.generateEntryElements($xmlInner, loadComments, $("#content"));
      });
    });
  };


  /*
    Notify the comment-viewer, when a microblog entry is selected.
   */

  loadComments = function(id) {
    if (typeof gadgets !== "undefined" && gadgets !== null) {
      iwcManager.sendIntent("MICROBLOG_ENTRY_SELECTED", id);
    }
  };

}).call(this);

//# sourceMappingURL=microblog-viewer.js.map